### ISSUE TITLE
Release 0.1.2 doesn't publish data

### ISSUE THREAD

**Issue by paulbovbel** [clearpathrobotics/LMS1xx#11]
When running on upstart, driver connects to sensor but doesn't publish /scan data. Taking the driver down and bringing it back up will cause /scan to start publishing as expected.

Likely catches the sensor in an inconsistent boot-up state.

**Comment by mikepurvis** [comment]
The retry loop which was added in 10274ffbabe0786f5d57e965a4adeb37e3232c78 made a wrong assumption that `laser.isConnected() == true` meant the system was fully up and initiailized. It looks like a secondary check must be added, which confirms data data is arriving at some frequency. If the sensor is not meeting the target frequency (or is zero), this logic should disconnect and reconnect.

**Comment by mikepurvis** [comment]
It seems like a very sensitive race condition, once again reinforcing my dislike of this codebase. In order to reproduce it from a source workspace, I had to build with the flags which are used in the release builds, eg:

    catkin_make -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCATKIN_BUILD_BINARY_PACKAGE=1

It isn't necessary to reboot to see the effect, though— simply depower the laser, and then turn it on after the driver has launched. The driver will repeatedly try (and fail) to open the socket; once it succeeds, the driver hangs in the [login function](https://github.com/clearpathrobotics/LMS1xx/blob/d31adbf5c40fdcbd461267d7fb164887f6f15e4e/src/LMS1xx.cpp#L118), due to the blocking read with no timeout. I tried adding an arbitrarily long timeout to the socket, which made it work for the initialization/login, but then caused problems during the main scanning operation.

Some possible options to move this forward:
- Set the socket timeout only for the duration of the login activity.
- Use select to time out just the login spot.
- Revert to the behaviour where the driver simply crashes on a bad startup, relying on roslaunch's optional respawn behaviour.

Really, though, I think the better thing would be to start from scratch, writing a modern driver which gets away from the C socket API, strtok everywhere, multiple reads, and the other curiosities which make this code so fragile.
